import type { Metadata } from "next";
import "./globals.css";
import TopBar from "./components/TopBar/TopBar";
import { HeroUIProvider } from "./components/HeroUIProvider/HeroUIProvidor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body>
        <HeroUIProvider>
          <div className="flex flex-col h-full">
            <TopBar />
            <div className="p-4 mt-16 mx-[12.5%] flex-1">
              {children}
            </div>
          </div>
        </HeroUIProvider>
      </body>
    </html >

  );
}
